name: Flexible CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        language: [python, node]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup ${{ matrix.language }} environment
        if: matrix.language == 'python'
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Setup ${{ matrix.language }} environment
        if: matrix.language == 'node'
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install dependencies
        if: matrix.language == 'python'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install dependencies
        if: matrix.language == 'node'
        run: npm install

      - name: Run tests
        if: matrix.language == 'python'
        run: pytest

      - name: Run tests
        if: matrix.language == 'node'
        run: npm test

  deploy:
    name: Deploy to Environment
    runs-on: ubuntu-latest

    needs: build_and_test

    steps:
      - name: Deploy to staging
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          echo "Deploying to staging environment"
          # Add deployment steps here for staging environment

      - name: Deploy to production
        if: github.event_name == 'push' && github.ref == 'refs/tags/v*'
        run: |
          echo "Deploying to production environment"
          # Add deployment steps here for production environment
